import { Auto, Turno } from './api'

// Mock data para autos
export const mockAutos: Auto[] = [
  {
    id: '1',
    marca: 'BMW',
    modelo: 'Serie 3',
    año: 2023,
    precio: 45000,
    kilometraje: 5000,
    color: 'Negro',
    combustible: 'Nafta',
    transmision: 'Automática',
    descripcion: 'BMW Serie 3 en excelente estado, con todos los servicios al día.',
    imagenUrl: '/images/bmw-serie3.jpg',
    estado: 'disponible',
  },
  {
    id: '2',
    marca: 'Mercedes-Benz',
    modelo: 'Clase C',
    año: 2022,
    precio: 52000,
    kilometraje: 12000,
    color: 'Blanco',
    combustible: 'Nafta',
    transmision: 'Automática',
    descripcion: 'Mercedes-Benz Clase C con equipamiento premium y tecnología de punta.',
    imagenUrl: '/images/mercedes-c.jpg',
    estado: 'disponible',
  },
  {
    id: '3',
    marca: 'Audi',
    modelo: 'A4',
    año: 2023,
    precio: 48000,
    kilometraje: 3000,
    color: 'Gris',
    combustible: 'Nafta',
    transmision: 'Automática',
    descripcion: 'Audi A4 último modelo, con sistema Quattro y full extras.',
    imagenUrl: '/images/audi-a4.jpg',
    estado: 'disponible',
  },
  {
    id: '4',
    marca: 'Porsche',
    modelo: 'Cayenne',
    año: 2023,
    precio: 95000,
    kilometraje: 1500,
    color: 'Rojo',
    combustible: 'Nafta',
    transmision: 'Automática',
    descripcion: 'Porsche Cayenne deportivo, potencia y elegancia en un solo vehículo.',
    imagenUrl: '/images/porsche-cayenne.jpg',
    estado: 'disponible',
  },
  {
    id: '5',
    marca: 'Tesla',
    modelo: 'Model 3',
    año: 2023,
    precio: 55000,
    kilometraje: 8000,
    color: 'Negro',
    combustible: 'Eléctrico',
    transmision: 'Automática',
    descripcion: 'Tesla Model 3 eléctrico, tecnología de vanguardia y cero emisiones.',
    imagenUrl: '/images/tesla-model3.jpg',
    estado: 'disponible',
  },
  {
    id: '6',
    marca: 'Volkswagen',
    modelo: 'Golf GTI',
    año: 2022,
    precio: 38000,
    kilometraje: 15000,
    color: 'Azul',
    combustible: 'Nafta',
    transmision: 'Manual',
    descripcion: 'VW Golf GTI deportivo, ideal para los amantes de la conducción.',
    imagenUrl: '/images/golf-gti.jpg',
    estado: 'disponible',
  },
]

// Mock data para turnos
export const mockTurnos: Turno[] = [
  {
    id: '1',
    clienteId: '1',
    clienteNombre: 'Juan Pérez',
    fecha: '2025-11-05',
    hora: '10:00',
    tipoServicio: 'Lavado Premium',
    estado: 'confirmado',
    vehiculo: 'BMW Serie 3',
    observaciones: 'Incluir encerado',
  },
  {
    id: '2',
    clienteId: '2',
    clienteNombre: 'María García',
    fecha: '2025-11-06',
    hora: '14:00',
    tipoServicio: 'Lavado Completo',
    estado: 'pendiente',
    vehiculo: 'Mercedes-Benz Clase C',
  },
  {
    id: '3',
    clienteId: '1',
    clienteNombre: 'Juan Pérez',
    fecha: '2025-10-28',
    hora: '11:00',
    tipoServicio: 'Lavado Express',
    estado: 'completado',
    vehiculo: 'Audi A4',
  },
]
